### ISSUE TITLE
Losing connection right after joining

### ISSUE THREAD

**Issue by Razorskills** [StarryPy/StarryPy#134]
I'm not sure what is going on here. possibly something that wasn't set in the configs? I've gotten this to work before though. But maybe its an actual bug. Maybe someone that works with the code will know.

It says the server tried to send "Welcome to the server! Play nice." and I know I didn't see that for the few seconds I was on the server.
```
aimgaming2@AIMGaming2:~$ cd /home/steam/StarryPy
aimgaming2@AIMGaming2:/home/steam/StarryPy$ python server.py
Attempting initialization of configuration manager singleton.
Setup console logging...
Setup file-based logging...
2015-05-23 16:11:09,151 - DEBUG - starrypy # Port check enabled. Performing port check to localhost:21024
2015-05-23 16:11:09,152 - DEBUG - starrypy # Port check succeeded. Continuing.
2015-05-23 16:11:09,152 - INFO - starrypy # Started StarryPy server version 1.5.1
2015-05-23 16:11:09,302 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'chat_logger'
2015-05-23 16:11:09,303 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'announcer_plugin'
2015-05-23 16:11:09,303 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'irc'
2015-05-23 16:11:09,304 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'command_dispatcher'
2015-05-23 16:11:09,304 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'mute_manager'
2015-05-23 16:11:09,304 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'new_player_greeter_plugin'
2015-05-23 16:11:09,305 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'planet_visitor_announcer_plugin'
2015-05-23 16:11:09,305 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'starbound_config_manager'
2015-05-23 16:11:09,305 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'motd_plugin'
2015-05-23 16:11:09,306 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'player_manager'
2015-05-23 16:11:09,306 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'plugin_manager'
2015-05-23 16:11:09,306 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'afk_plugin'
2015-05-23 16:11:09,307 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'user_management_commands'
2015-05-23 16:11:09,307 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'uptime_plugin'
2015-05-23 16:11:09,308 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'emotes_plugin'
2015-05-23 16:11:09,308 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'bookmarks_plugin'
2015-05-23 16:11:09,309 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'colored_names_plugin'
2015-05-23 16:11:09,309 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'poi_plugin'
2015-05-23 16:11:09,309 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'fuelgiver_plugin'
2015-05-23 16:11:09,309 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'starteritems_plugin'
2015-05-23 16:11:09,310 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'warpy_plugin'
2015-05-23 16:11:09,310 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'partychat_plugin'
2015-05-23 16:11:09,311 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'web_gui'
2015-05-23 16:11:09,312 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'brutus_whisper'
2015-05-23 16:11:09,322 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'planet_protect'
2015-05-23 16:11:09,322 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'admin_messenger'
2015-05-23 16:11:09,323 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'mod_chatter'
2015-05-23 16:11:09,324 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'loginwho_plugin'
2015-05-23 16:11:09,324 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'players_plugin'
2015-05-23 16:11:09,325 - DEBUG - starrypy.plugin_manager.PluginManager # Instantiated plugin 'claims'
2015-05-23 16:11:09,325 - DEBUG - starrypy.plugins.chat_logger # chat_logger plugin object activated.
2015-05-23 16:11:09,325 - DEBUG - starrypy.plugins.announcer_plugin # announcer_plugin plugin object activated.
2015-05-23 16:11:09,325 - DEBUG - starrypy.plugins.command_dispatcher # command_dispatcher plugin object activated.
2015-05-23 16:11:09,325 - DEBUG - starrypy.plugins.mute_manager # mute_manager plugin object activated.
2015-05-23 16:11:09,325 - DEBUG - starrypy.plugins.planet_visitor_announcer_plugin # planet_visitor_announcer_plugin plugin object activated.
2015-05-23 16:11:09,325 - DEBUG - starrypy.plugins.starbound_config_manager # starbound_config_manager plugin object activated.
2015-05-23 16:11:09,326 - DEBUG - starrypy.plugins.motd_plugin # motd_plugin plugin object activated.
2015-05-23 16:11:09,326 - DEBUG - starrypy.plugins.player_manager # player_manager plugin object activated.
2015-05-23 16:11:09,331 - INFO - starrypy.player_manager.manager # Loading player database.
2015-05-23 16:11:09,353 - DEBUG - starrypy.plugins.plugin_manager # plugin_manager plugin object activated.
2015-05-23 16:11:09,355 - DEBUG - starrypy.plugins.afk_plugin # afk_plugin plugin object activated.
2015-05-23 16:11:09,355 - DEBUG - starrypy.plugins.user_management_commands # user_management_commands plugin object activated.
2015-05-23 16:11:09,361 - DEBUG - starrypy.plugins.uptime_plugin # uptime_plugin plugin object activated.
2015-05-23 16:11:09,361 - DEBUG - starrypy.plugins.emotes_plugin # emotes_plugin plugin object activated.
2015-05-23 16:11:09,361 - DEBUG - starrypy.plugins.bookmarks_plugin # bookmarks_plugin plugin object activated.
2015-05-23 16:11:09,361 - DEBUG - starrypy.plugins.colored_names_plugin # colored_names_plugin plugin object activated.
2015-05-23 16:11:09,363 - DEBUG - starrypy.plugins.poi_plugin # poi_plugin plugin object activated.
2015-05-23 16:11:09,363 - DEBUG - starrypy.plugins.warpy_plugin # warpy_plugin plugin object activated.
2015-05-23 16:11:09,363 - DEBUG - starrypy.plugins.partychat_plugin # partychat_plugin plugin object activated.
2015-05-23 16:11:09,363 - DEBUG - starrypy.plugins.web_gui # web_gui plugin object activated.
2015-05-23 16:11:09,366 - INFO - starrypy.plugins.web_gui # WebGUI listening on port 8083
2015-05-23 16:11:09,367 - DEBUG - starrypy.plugins.brutus_whisper # brutus_whisper plugin object activated.
2015-05-23 16:11:09,367 - DEBUG - starrypy.plugins.planet_protect # planet_protect plugin object activated.
2015-05-23 16:11:09,368 - DEBUG - starrypy.plugins.admin_messenger # admin_messenger plugin object activated.
2015-05-23 16:11:09,370 - DEBUG - starrypy.plugins.mod_chatter # mod_chatter plugin object activated.
2015-05-23 16:11:09,370 - DEBUG - starrypy.plugins.loginwho_plugin # loginwho_plugin plugin object activated.
2015-05-23 16:11:09,370 - DEBUG - starrypy.plugins.players_plugin # players_plugin plugin object activated.
2015-05-23 16:11:09,370 - DEBUG - starrypy.plugins.claims # claims plugin object activated.
2015-05-23 16:11:09,370 - INFO - starrypy.plugin_manager.PluginManager # Loaded plugins:
afk_plugin, Active: True
user_management_commands, Active: True
uptime_plugin, Active: True
emotes_plugin, Active: True
bookmarks_plugin, Active: True
chat_logger, Active: True
colored_names_plugin, Active: True
announcer_plugin, Active: True
loginwho_plugin, Active: True
poi_plugin, Active: True
fuelgiver_plugin, Active: False
starteritems_plugin, Active: False
players_plugin, Active: True
irc, Active: False
warpy_plugin, Active: True
partychat_plugin, Active: True
starbound_config_manager, Active: True
command_dispatcher, Active: True
web_gui, Active: True
mute_manager, Active: True
new_player_greeter_plugin, Active: False
brutus_whisper, Active: True
motd_plugin, Active: True
player_manager, Active: True
plugin_manager, Active: True
claims, Active: True
planet_visitor_announcer_plugin, Active: True
planet_protect, Active: True
admin_messenger, Active: True
mod_chatter, Active: True
2015-05-23 16:11:09,374 - VDEBUG - starrypy # Reaping dead connections.
2015-05-23 16:11:09,374 - VDEBUG - starrypy # No connections reaped.
2015-05-23 16:11:09,374 - DEBUG - starrypy # Factory created, endpoint of port 21025
2015-05-23 16:11:09,374 - DEBUG - starrypy # Attempting to listen on TCP port 21025
2015-05-23 16:11:09,376 - INFO - starrypy # Listening on port 21025
2015-05-23 16:11:16,016 - VDEBUG - starrypy # Building protocol to address IPv4Address(TCP, '172.16.1.63', 51831)
2015-05-23 16:11:16,016 - VDEBUG - starrypy # Creating protocol with ID b81282168255440abfe6626093722bc6.
2015-05-23 16:11:16,016 - DEBUG - starrypy # Trying to initialize configuration manager.
2015-05-23 16:11:16,016 - INFO - starrypy # Connection established from IP: 172.16.1.63
2015-05-23 16:11:16,016 - VDEBUG - starrypy # Client protocol instantiated.
2015-05-23 16:11:16,021 - VDEBUG - starrypy # Building protocol in StarboundClientFactory to address IPv4Address(TCP, '127.0.0.1', 21024)
2015-05-23 16:11:16,021 - DEBUG - starrypy # Client protocol instantiated.
2015-05-23 16:11:16,038 - ERROR - starrypy.plugins.player_manager # Exception in on_connect_response, player info may not have been logged.
Traceback (most recent call last):
  File "/home/steam/StarryPy/plugins/core/player_manager/plugin.py", line 114, in on_connect_response
    connection_parameters = connect_response().parse(data.data)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 188, in parse
    return self.parse_stream(BytesIO(data))
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 398, in _parse
    return _read_stream(stream, self.lengthfunc(context))
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 305, in _read_stream
    raise FieldError("expected %d, found %d" % (length, len(data)))
FieldError: expected 6182, found 41
2015-05-23 16:11:16,048 - ERROR - starrypy.plugins.announcer_plugin # Unknown error in after_connect_response.
Traceback (most recent call last):
  File "/home/steam/StarryPy/plugins/announcer_plugin/announcer_plugin.py", line 17, in after_connect_response
    c = connect_response().parse(data.data)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 188, in parse
    return self.parse_stream(BytesIO(data))
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 398, in _parse
    return _read_stream(stream, self.lengthfunc(context))
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 305, in _read_stream
    raise FieldError("expected %d, found %d" % (length, len(data)))
FieldError: expected 6182, found 41
2015-05-23 16:11:16,049 - ERROR - starrypy.plugin_manager.PluginManager # Error in plugin <Plugin instance: loginwho_plugin (version .1)> with function after_connect_response.
Traceback (most recent call last):
  File "/home/steam/StarryPy/plugin_manager.py", line 166, in do
    res = getattr(plugin, command, lambda _: True)(data)
  File "/home/steam/StarryPy/plugins/loginwho_plugin/loginwho_plugin.py", line 18, in after_connect_response
    self.user_commands.who(data)
  File "/home/steam/StarryPy/plugins/core/player_manager/manager.py", line 444, in wrapped_function
    if self.protocol.player.access_level >= level:
AttributeError: 'NoneType' object has no attribute 'access_level'
2015-05-23 16:11:16,049 - VDEBUG - starrypy # Built chat payload. Data: 010000000000002157656c636f6d6520746f20746865207365727665722120506c6179206e6963652e
2015-05-23 16:11:16,049 - VDEBUG - starrypy # Built chat packet. Data: 0452010000000000002157656c636f6d6520746f20746865207365727665722120506c6179206e6963652e
2015-05-23 16:11:16,049 - VDEBUG - starrypy # Sent chat message with text: Welcome to the server! Play nice.
2015-05-23 16:11:16,920 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:16,920 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:16,922 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:16,924 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:16,964 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:16,981 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,032 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,081 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,131 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,182 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,233 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,282 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,332 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,386 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,432 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,482 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,533 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,582 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,632 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,683 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,732 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,783 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,833 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-05-23 16:11:17,866 - ERROR - starrypy.packet_stream.PacketStream # Decompression error in check_packet.
2015-05-23 16:11:17,866 - DEBUG - starrypy.packet_stream.PacketStream # Parsed packet:
2015-05-23 16:11:17,866 - DEBUG - starrypy.packet_stream.PacketStream # Container({'payload_size': -8, 'data': '\xf37\x02\x11\x14\x91Sx', 'id': 229})
2015-05-23 16:11:17,866 - DEBUG - starrypy.packet_stream.PacketStream # Packet data:
2015-05-23 16:11:17,883 - INFO - starrypy # Lost connection from IP: 172.16.1.63
2015-05-23 16:11:19,374 - VDEBUG - starrypy # Reaping dead connections.
2015-05-23 16:11:19,374 - VDEBUG - starrypy # No connections reaped.
2015-05-23 16:11:29,374 - VDEBUG - starrypy # Reaping dead connections.
2015-05-23 16:11:29,374 - VDEBUG - starrypy # No connections reaped.
```

**Comment by PowerMakc** [comment]
Hi! Protocol 668 - all ok, but Steam version (protokol 679) server gives erors. I can not go to the server. Always single error about server-client lost connection. Any idea how to fix it?


2015-06-03 22:46:11,238 - DEBUG - starrypy # Factory created, endpoint of port 21025
2015-06-03 22:46:11,238 - DEBUG - starrypy # Attempting to listen on TCP port 21025
2015-06-03 22:46:11,238 - INFO - starrypy # Listening on port 21025

2015-06-03 22:46:21,684 - DEBUG - starrypy # Trying to initialize configuration manager.
2015-06-03 22:46:21,685 - INFO - starrypy # Connection established from IP: 213.222.250.210
2015-06-03 22:46:21,687 - DEBUG - starrypy # Client protocol instantiated.
2015-06-03 22:46:21,881 - ERROR - starrypy.plugins.player_manager # Exception in on_connect_response, player info may not have been logged.
Traceback (most recent call last):
  File "/home/servers/starbound-cmd/plugins/core/player_manager/plugin.py", line 114, in on_connect_response
    connection_parameters = connect_response().parse(data.data)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 188, in parse
    return self.parse_stream(BytesIO(data))
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 398, in _parse
    return _read_stream(stream, self.lengthfunc(context))
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 305, in _read_stream
    raise FieldError("expected %d, found %d" % (length, len(data)))
FieldError: expected 3583413953362, found 36
2015-06-03 22:46:21,892 - ERROR - starrypy.plugins.announcer_plugin # Unknown error in after_connect_response.
Traceback (most recent call last):
  File "/home/servers/starbound-cmd/plugins/announcer_plugin/announcer_plugin.py", line 17, in after_connect_response
    c = connect_response().parse(data.data)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 188, in parse
    return self.parse_stream(BytesIO(data))
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 398, in _parse
    return _read_stream(stream, self.lengthfunc(context))
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 305, in _read_stream
    raise FieldError("expected %d, found %d" % (length, len(data)))
FieldError: expected 3583413953362, found 36
2015-06-03 22:46:21,892 - ERROR - starrypy.plugin_manager.PluginManager # Error in plugin <Plugin instance: loginwho_plugin (version .1)> with function after_connect_response.
Traceback (most recent call last):
  File "/home/servers/starbound-cmd/plugin_manager.py", line 166, in do
    res = getattr(plugin, command, lambda _: True)(data)
  File "/home/servers/starbound-cmd/plugins/loginwho_plugin/loginwho_plugin.py", line 18, in after_connect_response
    self.user_commands.who(data)
  File "/home/servers/starbound-cmd/plugins/core/player_manager/manager.py", line 444, in wrapped_function
    if self.protocol.player.access_level >= level:
AttributeError: 'NoneType' object has no attribute 'access_level'
2015-06-03 22:46:23,049 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,430 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,431 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,433 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,434 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,607 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,657 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,709 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,758 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,809 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,857 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,910 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:23,957 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:24,003 - ERROR - starrypy.packet_stream.PacketStream # Decompression error in check_packet.
2015-06-03 22:46:24,003 - DEBUG - starrypy.packet_stream.PacketStream # Parsed packet:
2015-06-03 22:46:24,004 - DEBUG - starrypy.packet_stream.PacketStream # Container({'payload_size': -14, 'data': '\x0f7\x02\x0b\x14\x93ux\x9c\xed\xdd\xd1j\xe2', 'id': 87})
2015-06-03 22:46:24,004 - DEBUG - starrypy.packet_stream.PacketStream # Packet data:
2015-06-03 22:46:24,014 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:24,052 - ERROR - starrypy.packet_stream.PacketStream # Decompression error in check_packet.
2015-06-03 22:46:24,052 - DEBUG - starrypy.packet_stream.PacketStream # Parsed packet:
2015-06-03 22:46:24,053 - DEBUG - starrypy.packet_stream.PacketStream # Container({'payload_size': 12, 'data': '\x86\xe1\x11\xbc\x90\\J\xeel\x0f\xf6\xdc', 'id': 64})
2015-06-03 22:46:24,053 - DEBUG - starrypy.packet_stream.PacketStream # Packet data:
2015-06-03 22:46:24,059 - WARNING - starrypy # Received unknown message ID (55) from client.
2015-06-03 22:46:24,075 - INFO - starrypy # Lost connection from IP: 213.222.250.210

**Comment by kamilion** [comment]
Protocol 679 was supported in a newer version.
The current version in the repository (StarryPy 1.7 for Protocol 691) should resolve the issue. Closing #134, please reopen or create a new issue if you continue to have a problem with 1.7.
