### ISSUE TITLE
Index out of range error from command plugin.

### ISSUE THREAD

**Issue by AllSystemsGo** [StarryPy/StarryPy#158]
```
2015-12-07 12:42:27,916 - INFO - starrypy.plugins.chat_logger # Chat message sent: <FlowerWhistle> /
2015-12-07 12:42:27,917 - ERROR - starrypy.plugin_manager.PluginManager # Error in plugin <Plugin instance: command_plugin (version .1)> with function on_chat_sent.
Traceback (most recent call last):
  File "/home/steam0/StarryPy/plugin_manager.py", line 209, in do
    res = getattr(plugin, command, lambda _: True)(data)
  File "/home/steam0/StarryPy/plugins/core/command_plugin/command_plugin.py", line 18, in on_chat_sent
    command = split_command[0]
IndexError: list index out of range
```

**Comment by kharidiron** [comment]
this is a harmless error in that, after the '/' is stripped out of the message, there is no message.

To fix, a quick check needs to be added before parsing continues.
