### ISSUE TITLE
can't start starrypy

### ISSUE THREAD

**Issue by Gartral** [StarryPy/StarryPy#172]
I keep getting

`Traceback (most recent call last):
  File "./server.py", line 18, in <module>
    from twisted.internet import reactor
  File "/home/steam/.local/lib/python2.7/site-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/home/steam/.local/lib/python2.7/site-packages/twisted/internet/default.py", line 16, in <module>
    from twisted.python.runtime import platform
ImportError: cannot import name platform`

when attempting to start starrypy

**Comment by kamilion** [comment]
Maybe you should try the starrypy version that's actually updated for versions past starbound 1.0?
https://github.com/StarryPy/StarryPy3k
