### ISSUE TITLE
Handling of "pings" from from server-lists

### ISSUE THREAD

**Issue by traxo-xx** [StarryPy/StarryPy#77]
I'm getting these errors, when starbound-servers.net checks if my server is online:

```
2014-02-03 16:25:39,012 - starrypy - INFO - Connection established from IP: 37.187.79.210
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/udp.py", line 234, in doRead
    self.protocol.datagramReceived(data, addr)
  File "server.py", line 623, in datagramReceived
    self.transport.write(datagram, (self.config.upstream_hostname, self.config.upstream_port))
exceptions.AttributeError: UDPProxy instance has no attribute 'config'
2014-02-03 16:25:39,016 - starrypy - INFO - Lost connection from IP: 37.187.79.210
2014-02-03 16:26:20,025 - starrypy.plugin_manager.PluginManager - ERROR - Error in plugin <Plugin instance: bouncer (version .1)> with function after_connect_response.
Traceback (most recent call last):
  File "/home/starbound/StarryPy/plugin_manager.py", line 169, in do
    res = getattr(plugin, command, lambda _: True)(data)
  File "/home/starbound/StarryPy/plugins/bouncer_plugin/bouncer_plugin.py", line 31, in after_connect_response
    if self.protocol.player.access_level < UserLevels.REGISTERED:
AttributeError: 'NoneType' object has no attribute 'access_level'
```

Might be related to https://github.com/CarrotsAreMediocre/StarryPy/issues/59

**Comment by kamilion** [comment]
We've tossed the whole UDP forwarder stuff. Instead, fix your starbound.config so "queryServerPort" remains on port 21025 and  "gameServerPort" is 21024.

Here's a sample starbound.config configuration so you can see what I mean.

```json
{
  "allowAdminCommands" : true,
  "allowAdminCommandsFromAnyone" : false,
  "allowAnonymousConnections" : true,
  "anonymousConnectionsAreAdmin" : false,
  "audioChannelSeparation" : [ -25, 25 ],
  "audioChannels" : 2,
  "bannedIPs" : [  ],
  "bannedUuids" : [  ],
  "checkAssetsDigest" : false,
  "clearPlayerFiles" : false,
  "clearUniverseFiles" : false,
  "configurationVersion" : 420,
  "crafting.filterHaveMaterials" : false,
  "fullscreen" : false,
  "fullscreenResolution" : [ 1920, 1080 ],
  "gameServerBind" : "*",
  "gameServerPort" : 21024,
  "maxFrameSkip" : 10,
  "maxPlayers" : 80,
  "maximized" : true,
  "maximizedResolution" : [ 1000, 600 ],
  "musicVol" : 100,
  "playerBackupFileCount" : 3,
  "queryServerBind" : "*",
  "queryServerPort" : 21025,
  "rconServerBind" : "*",
  "rconServerPassword" : "theconsolepassword",
  "rconServerPort" : 21026,
  "rconServerTimeout" : 1000,
  "renderSleep" : true,
  "runQueryServer" : true,
  "runRconServer" : true,
  "safeScripts" : true,
  "sampleRate" : 44100,
  "serverName" : "Zurfa.net Public Server",
  "serverUsers" : {
      "amazingadmin" : {
          "admin" : true,
          "password" : "theadminpassword"
      },
      "guest" : {
          "admin" : false,
          "password" : "hunter2"
      },
      "registered" : {
          "admin" : false,
          "password" : "hunter2"
      }
  },
  "sfxVol" : 100,
  "speechBubbles" : true,
  "title.connectionAddress" : "",
  "title.connectionPort" : "",
  "title.connectionString" : "",
  "upnpPortForwarding" : true,
  "vsync" : true,
  "windowTitle" : "Starbound - Beta",
  "windowedResolution" : [ 1000, 600 ],
  "zoomLevel" : 3
}
```
