### ISSUE TITLE
Warping lag on unclean player disconnect/reconnect

### ISSUE THREAD

**Issue by traxo-xx** [StarryPy/StarryPy#81]
I'm not exactly sure what happened, but judging by the log entries the play probably disconnected in an unclean way and the server didn't notice. Maybe his client crashed. When he tried to reconnect it didn't work and for some reason all players on the server had problems with warping to ships or planets. Every warp took like 30 seconds.

```
2014-02-04 21:06:53,512 - starrypy.plugins.player_manager - INFO - Player Cpt Bagel is now on a ship.
2014-02-04 21:07:06,853 - starrypy.plugins.player_manager - INFO - Player Gical is now on a ship.
2014-02-04 21:07:11,436 - starrypy.plugins.player_manager - INFO - Player Gical is now on a ship.
2014-02-04 21:14:01,888 - starrypy.plugins.player_manager - INFO - Player Baron v Fleischgeschuetz is now on a ship.
2014-02-04 21:14:42,948 - starrypy.plugins.player_manager - INFO - Player Gical is now on a ship.
2014-02-04 21:15:18,213 - starrypy - INFO - Connection established from IP: xxx.xxx.xxx.xxx
2014-02-04 21:15:18,704 - starrypy.plugins.player_manager - INFO - Player tried to log in with name Cpt. Bagel, replaced with Cpt Bagel.
2014-02-04 21:15:18,709 - starrypy.plugins.player_manager - INFO - Already logged in user tried to log in.
2014-02-04 21:15:18,710 - starrypy - ERROR - Couldn't disconnect protocol.
2014-02-04 21:15:18,710 - starrypy - INFO - Lost connection from IP: xxx.xxx.xxx.xxx
2014-02-04 21:15:32,074 - starrypy - INFO - Connection established from IP: xxx.xxx.xxx.xxx
2014-02-04 21:15:59,895 - starrypy.plugins.player_manager - INFO - Player tried to log in with name Cpt. Bagel, replaced with Cpt Bagel.
2014-02-04 21:15:59,900 - starrypy.plugins.player_manager - INFO - Already logged in user tried to log in.
2014-02-04 21:15:59,902 - starrypy - ERROR - Couldn't disconnect protocol.
2014-02-04 21:15:59,903 - starrypy - INFO - Lost connection from IP: xxx.xxx.xxx.xxx
2014-02-04 21:16:42,164 - starrypy.plugins.player_manager - INFO - Player Baron v Fleischgeschuetz is now on a ship.
2014-02-04 21:16:48,106 - starrypy.plugins.player_manager - INFO - Player Crowborn is now on a ship.
2014-02-04 21:16:50,942 - starrypy - INFO - Connection established from IP: xxx.xxx.xxx.xxx
2014-02-04 21:16:51,410 - starrypy.plugins.player_manager - INFO - Player tried to log in with name Cpt. Bagel, replaced with Cpt Bagel.
2014-02-04 21:16:51,415 - starrypy.plugins.player_manager - INFO - Already logged in user tried to log in.
2014-02-04 21:16:51,417 - starrypy - ERROR - Couldn't disconnect protocol.
2014-02-04 21:16:51,417 - starrypy - INFO - Lost connection from IP: xxx.xxx.xxx.xxx
2014-02-04 21:17:21,183 - starrypy.plugins.chat_logger - INFO - Chat message sent: <Gical> Yo
^[2014-02-04 21:19:00,186 - starrypy - INFO - Connection established from IP: xxx.xxx.xxx.xxx
2014-02-04 21:19:00,654 - starrypy.plugins.player_manager - INFO - Player tried to log in with name Cpt. Bagel, replaced with Cpt Bagel.
2014-02-04 21:19:00,658 - starrypy.plugins.player_manager - INFO - Already logged in user tried to log in.
2014-02-04 21:19:00,659 - starrypy - ERROR - Couldn't disconnect protocol.
2014-02-04 21:19:00,660 - starrypy - INFO - Lost connection from IP: xxx.xxx.xxx.xxx
2014-02-04 21:19:43,343 - starrypy.plugins.player_manager - INFO - Player Crowborn is now on a ship.
2014-02-04 21:20:11,817 - starrypy.plugins.player_manager - INFO - Player Crowborn is now on a ship.
```

Then I kicked the player so he can reconnect. The result was this:

```
2014-02-04 21:21:23,780 - starrypy.plugins.chat_logger - INFO - Chat message sent: <Crowborn> /kick "Cpt Bagel"
2014-02-04 21:21:23,785 - starrypy.plugins.player_manager - INFO - Player disconnected: Cpt Bagel
2014-02-04 21:21:23,788 - starrypy - INFO - Lost connection from IP: xxx.xxx.xxx.xxx
2014-02-04 21:21:23,788 - starrypy.plugins.command_dispatcher - ERROR - Error in on_chat_sent.
Traceback (most recent call last):
  File "/home/starbound/StarryPy/plugins/core/command_plugin/command_plugin.py", line 22, in on_chat_sent
    self.commands[command](split_command[1:])
  File "/home/starbound/StarryPy/plugins/core/player_manager/manager.py", line 243, in wrapped_function
    return f(self, *args, **kwargs)
  File "/home/starbound/StarryPy/plugins/core/admin_commands_plugin/admin_command_plugin.py", line 157, in kick
    (self.protocol.player.name,
AttributeError: 'NoneType' object has no attribute 'name'
2014-02-04 21:21:23,789 - starrypy.plugin_manager.PluginManager - ERROR - Error in plugin <Plugin instance: command_dispatcher (version .1)> with function on_chat_sent.
Traceback (most recent call last):
  File "/home/starbound/StarryPy/plugin_manager.py", line 169, in do
    res = getattr(plugin, command, lambda _: True)(data)
  File "/home/starbound/StarryPy/plugins/core/command_plugin/command_plugin.py", line 22, in on_chat_sent
    self.commands[command](split_command[1:])
  File "/home/starbound/StarryPy/plugins/core/player_manager/manager.py", line 243, in wrapped_function
    return f(self, *args, **kwargs)
  File "/home/starbound/StarryPy/plugins/core/admin_commands_plugin/admin_command_plugin.py", line 157, in kick
    (self.protocol.player.name,
AttributeError: 'NoneType' object has no attribute 'name'
2014-02-04 21:21:23,791 - starrypy - ERROR - Couldn't disconnect protocol.
2014-02-04 21:21:23,791 - starrypy - INFO - Lost connection from IP: xxx.xxx.xxx.xxx
Unhandled Error
Traceback (most recent call last):
  File "server.py", line 682, in <module>
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 299, in connectionLost
    protocol.connectionLost(reason)
  File "server.py", line 448, in connectionLost
    self.logger.trace("Protocol was not in factory list. This should not happen.")
exceptions.AttributeError: StarryPyServerProtocol instance has no attribute 'logger'
```

I'm using the current master branch.

**Comment by kamilion** [comment]
This issue is long out of date. If it's still relevant, please reopen it or file a new issue. Closing #81.
